# PID params for Ardupilot setPose pose control
pid:
  ros: true
  x:
    kp: 0.7
    ki: 0.05
    kd: 0.1
    min_sat: -2
    max_sat: 2
    min_wind: -5
    max_wind: 5
  y:
    kp: 0.7
    ki: 0.05
    kd: 0.1
    min_sat: -2
    max_sat: 2
    min_wind: -5
    max_wind: 5
  z:
    kp: 0.7
    ki: 0.05
    kd: 0.05
    min_sat: -1
    max_sat: 1
    min_wind: -3
    max_wind: 3
  yaw:
    ki: 0.05
    kp: 1
    min_sat: -2
    kd: 0
    max_sat: 2
    min_wind: -1.57
    max_wind: 1.57